name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      -
        name: Run the tests
        run: bun run test functional integration
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      -
        name: Lint project
        run: bun run lint
